### ISSUE TITLE
settingtypes.txt: malformed properties

### ISSUE THREAD

**Issue by mazes-80** [fluxionary/minetest-limit_physics_monoids#1]
Should be quite straightforward to fix, but until now client outputs error:

`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:speed_folder (speed folder) enum multiply add,max,multiply"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:speed_folder_initial (speed folder initial value) float 1"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:speed_limiter (speed limiter) enum log__n none,gamma,tanh,log__n"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:speed_param_1 (speed limiter parameter 1) float 2"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:speed_param_2 (speed limiter parameter 2) float 0.1"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:jump_folder (jump folder) enum multiply add,max,multiply"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:jump_folder_initial (jump folder initial value) float 1"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:jump_limiter (jump limiter) enum tanh none,gamma,tanh,log__n"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:jump_param_1 (jump limiter parameter 1) float 1"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:jump_param_2 (jump limiter parameter 2) float 0"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:gravity_folder (gravity folder) enum multiply add,max,multiply"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:gravity_folder_initial (gravity folder initial value) float 1"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:gravity_limiter (gravity limiter) enum none none,gamma,tanh,log__n"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:gravity_param_1 (gravity limiter parameter 1) float 1"`
`2024-08-17 03:07:36: ERROR[Main]: Invalid line in .minetest/mods/limit_physics_monoids/settingtypes.txt "limit_physics_monoids:gravity_param_2 (gravity limiter parameter 2) float 0"`

**Comment by fluxionary** [comment]
problem seemed to be the ':' in the setting name. i suppose i never checked mod settings through the GUI, gotta fix all my other mods too. thanks for the note. it might take a day or so for this to get updated in the content db.
